### ISSUE TITLE
[merged, needs testing] support for gradle/zipflinger signing

### ISSUE THREAD

**Issue by obfusk** [obfusk/apksigcopier#52]
Support was merged in #57 :tada: but we could use more examples to test!

---

### Help wanted

- [x] we could use more examples of gradle-signed APKs (and their unsigned original APKs) for testing.
- [x] we need to find out *why* `zipflinger` adds the 132-byte virtual entry to these APKs.

### Related

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11874#note_1136363987
https://gitlab.com/fdroid/fdroidserver/-/issues/1051

### TODO

- [x] what are the differences?
  - [x] `META-INF/{MANIFEST.MF,*.SF,*.RSA}` ZIP metadata (`0.0` vs `2.0`, `unx` vs `fat`, permissions `0666`/`0644` vs `0600`).
    - [x] `create_system=3` instead of `0`.
    - [x] `create_version=0` instead of `20`.
    - [x] `external_attr=0o100666 << 16` instead of `0`, or
    - [x] `external_attr=0o100644 << 16` instead of `0`.
    - [x] `extract_version=0` instead of `20`.
    - [x] `flag_bits=0` instead of `0x800`.
    - [x] `compresslevel=1` instead of `9`.
  - [x] a ZIP local file header with an empty file name and 102 bytes of zeroes in its extra field at the start of the file.
    - [x] why is is there? [we know it's created by `zipflinger`/`signflinger` and most likely why]
  - [x] ZIP alignment?! [seems OK so far]
  - [x] anything else? [not so far]
  - [x] consistent and reproducible? [yes, but only 2 APKs found in the wild so far]
- [x] autodetect somehow?

**Comment by jugendhacker** [comment]
Maybe https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-main/signflinger/ helps with finding out why there is this local file header

**Comment by obfusk** [comment]
@jugendhacker thx!

I still can't figure out *why* it's there in some APKs (but not *all* APKs that use `zipflinger`), or why it's 132 bytes (in the 2 APKs I've seen so far).

But these "virtual entries" definitely come from `zipflinger`: [`LocalFileHeader.java`](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-main/zipflinger/src/com/android/zipflinger/LocalFileHeader.java#61) & [`ZipArchive.java`](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-main/zipflinger/src/com/android/zipflinger/ZipArchive.java#268).

**Comment by obfusk** [comment]
Code for determining whether APK files start with a virtual entry:

```bash
$ for x in *.apk; do echo "$(head -c28 "$x" | shasum | cut -c-40) $x" | grep 7170680469ab42a97fe39d10011c5b72971a57a4; done
```

**Comment by obfusk** [comment]
I think I figured out the mystery "virtual entry" :tada:

Most likely this is a default manifest ZIP entry created and later deleted (and thus eventually replaced by a virtual entry) by `signflinger`/`zipflinger`:

```py
>>> (30 + len("META-INF/MANIFEST.MF") +
...       len("Manifest-Version: 1.0\r\n"
...           "Created-By: Android Gradle 7.1.3\r\n"
...           "Built-By: Signflinger\r\n\r\n"))
132
```

See [`SignedApk.java`](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-main/signflinger/src/com/android/signflinger/SignedApk.java#118).

**Comment by obfusk** [comment]
[Change from `0666` to `0664`](https://android.googlesource.com/platform/tools/base/+/895ba5fba6ab84617dd67e38f456a8f96aa37ff0%5E%21/#F0)
